name: Notes Application CI Pipeline
# create a CI pipeline based on the assignment specification
# remember to commit often

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    defaults:
      run:
        working-directory: src
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
    env:
      SERVER: mongodb://localhost:27017
      PORT: 3000
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Install Deps
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start Application
        run: npm run start &
      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000
      - name: Run end-to-end tests with log report
        run: npm run test:e2e --reporter=list
      - name: Upload Playwright Report
        if: always() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v7
        with:
          name: playwright-report
          path: src/playwright-report/
          retention-days: 7

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Install Deps
        run: npm install
      - name: Run Lint
        run: npm run test:lint

  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Install Deps
        run: npm install
      - name: Run Unit Tests
        run: npm run test:unit

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    needs: [lint, unit-test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Install Deps
        run: npm install
      - name: Package Application
        run: |
          mkdir deploy-artifact
          cp -r app.js routes models views package.json package-lock.json deploy-artifact/
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: app-package
          path: src/deploy-artifact/
